### ISSUE TITLE
Simply doesn't work

### ISSUE THREAD

**Issue by hrqmonteiro** [drzel/vim-scroll-in-place#1]
I installed using a plugin manager. Should i do something else? Cause is not working at all.

**Comment by drzel** [comment]
Yep you need to add it to your status line. The readme has instructions.

**Comment by drzel** [comment]
ctrl-j and ctrl-k should now let you scroll in place in normal and visual mode. Are these keys mapped to something else for you?

**Comment by hrqmonteiro** [comment]
No, they are not mapped to nothing else.

I even created a minimal vim config, with no other plugins activated, no keys mapping. Started it using the `vim -u ` option selecting it. And still doesn't work.

**Comment by drzel** [comment]
Interesting. I've only tested on neovim 0.4. Which version of vim are you using?

**Comment by hrqmonteiro** [comment]
I am using the Neovim nightly

```
NVIM v0.5.0-dev+944-g82100a6bd
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/hrq/neovim/build/config -I/home/hrq/neovim/src -I/home/hrq/neovim/.deps/usr/include -I/usr/include -I/home/hrq/neovim/build/src/nvim/auto -I/home/hrq/neovim/build/include
Compiled by hrq@motherbase

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

```

**Comment by drzel** [comment]
Does the `:map` command return any of the following?:
```
v  <NL>        * <Esc>:call <SNR>27_Saving_scroll("gv1<C-V><C-D>")<CR>                                                                                                                         
n  <NL>        * :call <SNR>27_Saving_scroll("1<C-V><C-D>")<CR>                                                                                                                                
v  <C-K>       * <Esc>:call <SNR>27_Saving_scroll("gv1<C-V><C-U>")<CR>                                                                                                                         
n  <C-K>       * :call <SNR>27_Saving_scroll("1<C-V><C-U>")<CR>
```

**Comment by hrqmonteiro** [comment]
It doesn't show none of that, just the mapping to my other plugins, like coc-nvim, emmet.vim, fzf, and stuff.

**Comment by drzel** [comment]
Are there other mappings defined for those keys?

**Comment by hrqmonteiro** [comment]
No, there are not.

**Comment by hrqmonteiro** [comment]
Well, i found out that these functions are natively in vim

`Ctrl + E` scrolls in place up, and `Ctrl + Y` scrolls in place down. Guess i'm using them now.

**Comment by drzel** [comment]
Kinda - scroll in place moves the page and the cursorline so it remains “in place” with respect to the window.
